steps:
  - name: 'gradle:8.13-jdk17'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd projects/crypto-autotrading-app
        ./gradlew clean shadowJar --no-daemon
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_ARTIFACT_REPOSITORY}/${_IMAGE_NAME}:${_SHORT_SHA}'
      - '-f'
      - 'docker/app/Dockerfile'
      - '.'
images:
  - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_ARTIFACT_REPOSITORY}/${_IMAGE_NAME}:${_SHORT_SHA}'
options:
  logging: CLOUD_LOGGING_ONLY
